
# rails向けチェックをする
Rails:
  Enabled: true

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# メソッド名のprefixに「set_」「get_」を許可
AccessorMethodName:
  Enabled: false

# frozen_string_literal: true無しを許可
Style/FrozenStringLiteralComment:
  Enabled: false

# Rubyの循環的複雑度(条件式の数)をチェック(デフォルトは6)
CyclomaticComplexity:
  Max: 10

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# クラスにコメントを残さない
Documentation:
  Enabled: false

# private, protected等のアクセス修飾子後、インデントを落とす
Layout/IndentationConsistency:
  EnforcedStyle: rails

# classの長さチェックを無効化
Metrics/ClassLength:
  Enabled: false

# LineLengthのコメント行を無効化
Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['\A#']
  Exclude:
    - config/routes.rb

# 名前付き引数の最低文字数を2にする(ip, uaを許可したい)
Naming/UncommunicativeMethodParamName:
  MinNameLength: 2

# [:symbol, :symbol]の形式を許可する %iを強制しない
Style/SymbolArray:
  Enabled: false

# 複雑さ制限を緩める
Metrics/AbcSize:
  Max: 35

# 「and」「or」の使用を許可
AndOr:
  Enabled: false




# メソッドの長さの許容数を変更する
Metrics/MethodLength:
  Max: 25
  Exclude:
    - config/routes.rb



# Routesのブロックの長さを制限しない
Metrics/BlockLength:
  Exclude:
    - config/routes.rb

# 除外するファイル
AllCops:
  Exclude:
    - Rakefile
    - db/schema.rb
    - config.ru
    - tmp/**/*
    - vendor/bundle/**/*