# -*- mode: ruby -*-
# vi: set ft=ruby :

# 仮想環境を利用するツールを設定
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# vagrant up時にVagrantのプラグインを自動でインストール
required_plugins = %w[vagrant-vbguest vagrant-disksize vagrant-winnfsd vagrant-bindfs vagrant-rsync-back vagrant-unison2]
_retry = false
required_plugins.each do |plugin|
  unless Vagrant.has_plugin? plugin
    system "vagrant plugin install #{plugin} --plugin-clean-sources --plugin-source http://rubygems.org/"
    _retry = true
  end
end

if _retry
  exec 'vagrant ' + ARGV.join(' ')
else
  puts 'All Plugin Dependencies already installed'
end

Vagrant.configure('2') do |config|
  # インストールするOSを設定
  config.vm.box = 'bento/centos-6.10'

  # IPアドレス割り当ての自動化(DHCP)
  config.vm.network :private_network, id: 'default-network', type: 'dhcp', ip: '192.168.34.0'

  # ポートフォワードの自動化
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh', auto_correct: true

  # ブリッジアダプター（DHCPによってIPアドレスを割当）=>他からも見れるように
  config.vm.network :public_network

  # サーバー設定
  config.disksize.size = '50GB'
  config.vm.boot_timeout = 600
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    # vb.name = 'test_vm'
    vb.cpus = 2
    vb.memory = 2048
    vb.customize [
      'modifyvm', :id,
      '--hwvirtex', 'on',
      '--nestedpaging', 'on',
      '--largepages', 'on',
      '--ioapic', 'on',
      '--pae', 'on',
      '--natdnsproxy1', 'off',
      '--natdnshostresolver1', 'off',
      '--paravirtprovider', 'kvm'
    ]
  end

  # 共有フォルダ
  config.vm.synced_folder "./rails", "/var/www/rails", mount_options: ['dmode=777','fmode=755']

  # config.vm.synced_folder "./rails", "/var/www/rails", type: "nfs", nfs_export: true, nfs_version: 3
  # config.vm.synced_folder ".", "/vagrant", mount_options: ['dmode=777','fmode=755']
  # config.vm.synced_folder "D:\\vagrant\\aiq", "/vagrant", mount_options: ['dmode=777','fmode=755']
  # config.vm.synced_folder "./", "/vagrant", owner: "root", group: "root"
  # config.vm.synced_folder 'C:\\Users\\KITM7581\\Downloads', '/mnt/Downloads',
  #                         type: 'virtualbox',
  #                         mount_options: ['dmode=775,fmode=644']

  # その１
  # ローカルマシンの Vagrantfile があるディレクトリ内の data フォルダと
  # 仮想マシン内の /vagrant_data ディレクトリを共有する
  # config.vm.synced_folder {host_path}, {guest_path}, option...
  # config.vm.synced_folder "./data", "/vagrant_data"
  # Vagrantfile上 Windows で絶対パスで指定するときバックスラッシュはエスケープする必要がある
  # config.vm.synced_folder "C:\\Vagrant\\centos7\\public_html", "/vagrant_data", owner: "vagrant", group: "www", type: "virtualbox"
  #
  # その２（NFS）
  # Windows で NFS の共有をする
  # Windows の場合、共有フォルダのタイプで NFS が指定できません……が、
  # vagrant-winnfsd というプラグインを追加することで対応できます。
  # 共有フォルダのタイプを nfs にする場合、owner と group は指定できないので注意
  # 次のようにエラーが出る
  # * Shared folders that have NFS enabled do not support owner/group
  # config.vm.synced_folder "./data/mysql", "/var/lib/mysql", type: "nfs", nfs_export: true, nfs_version: 3
  #
  # その３（rsync）
  #  config.vm.synced_folder "./data", "/vagrant_data", type: "rsync", rsync__exclude: [".git/"]
  #
  # その４（smb）
  # Windows で利用する場合は PowerShell v3 以上が必須
  # config.vm.synced_folder "./data", "/vagrant_data", type: "smb", smb_host: "192.168.0.15", smb_password: hogehoge, smb_username: "fugafuga"

  config.winnfsd.uid = 1000
  config.winnfsd.gid = 1000

  # shell
  config.vm.provision 'shell', inline: <<-SHELL
    # 開発パッケージ
    wget https://raw.githubusercontent.com/fukuda-free/linux_shell/master/centOS6/develop_package_install.sh
    . develop_package_install.sh

    # mysql
    wget https://raw.githubusercontent.com/fukuda-free/linux_shell/master/centOS6/develop_mysql57_install.sh
    . develop_mysql57_install.sh

    # ruby install(2.4 or 2.5 or 2.6)
    wget https://raw.githubusercontent.com/fukuda-free/linux_shell/master/centOS6/ruby_on_rbenv_install.sh
    . ruby_on_rbenv_install.sh 2.4

    # rails insltall(4.2 or 5.1 or 5.2)
    # wget https://raw.githubusercontent.com/fukuda-free/linux_shell/master/centOS6/rails_install.sh
    # . rails_install.sh 4.2

    # node install(8 or 9 or 10 or 11 or 12)
    wget https://raw.githubusercontent.com/fukuda-free/linux_shell/master/centOS6/node_on_nvm_install.sh
    . node_on_nvm_install.sh 10

    # mecab
    # https://raw.githubusercontent.com/fukuda-free/linux_shell/develop/centOS6/mecab_on_ipadic_neologd_install.sh
    # . mecab_on_ipadic_neologd_install.sh

    echo 'git のバージョンは以下となります'
    git --version
    echo ''
    echo 'ruby のバージョンは以下となります'
    ruby -v
    echo ''
    echo 'rails のバージョンは以下となります'
    rails -v
    echo ''
    echo 'node.js のバージョンは以下となります'
    node -v
    echo ''
    echo 'npm のバージョンは以下となります'
    npm -v
    echo ''
    echo 'yarn のバージョンは以下となります'
    yarn -v
    echo ''
  SHELL
end
