# -*- mode: ruby -*-
# vi: set ft=ruby :

# 仮想環境を利用するツールを設定
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# Vagrantのプラグインを自動でインストール
unless Vagrant.has_plugin?('vagrant-multiplug')
  system 'vagrant plugin install vagrant-multiplug'
end

Vagrant.configure('2') do |config|
  # インストールするOSを設定
  config.vm.box = 'centos/6'
  # config.vm.box = 'centos/7'

  # 他で使うプラグインをインストール（「vagrant-multiplug」が無いと動かない）
  if Vagrant.has_plugin?('vagrant-multiplug')
    config.plugin.add_dependency  'vagrant-vbguest'
    config.plugin.add_dependency  'vagrant-disksize' # HDDの容量を変更できる
    config.plugin.add_dependency  'vagrant-winnfsd' # WindowsでNFS機能が使用できる
    config.plugin.add_dependency  'vagrant-bindfs'
    config.plugin.add_dependency  'vagrant-rsync-back'
    config.plugin.add_dependency  'vagrant-unison2'
    config.plugin.add_dependency  'vagrant-cachier'
    config.plugin.add_dependency  'vagrant-hostmanager' # hosts設定ができる（ホストOS、ゲストOS できる）
    config.plugin.add_dependency  'vagrant-docker-compose' # docker関係をインストールしてくれる
    config.plugin.add_dependency  'vagrant-gatling-rsync' # rsyncを高速化するプラグインvagrant-gatling-rsync
    config.plugin.add_dependency  'vagrant-auto_network' # ネットワークを自動割り当てに

    # プラグイン別の設定
    # config.cache.scope = :box if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :machine if Vagrant.has_plugin?('vagrant-cachier')
    config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')
    if Vagrant.has_plugin?('vagrant-gatling-rsync')
      config.gatling.latency = 0.2
      config.gatling.time_format = '%H:%M:%S'
      config.gatling.rsync_on_startup = false
    end

    if Vagrant.has_plugin?('vagrant-hostmanager')
      config.hostmanager.enabled = true
      config.hostmanager.manage_host = true
      config.hostmanager.ignore_private_ip = false
      config.hostmanager.include_offline = false
      config.vm.hostname = 'test.local'
    end
  end

  # IPアドレス割り当ての自動化(DHCP)
  config.vm.network :private_network, auto_network: true, auto_correct: true

  # ブリッジアダプター（DHCPによってIPアドレスを割当）=>他からも見れるように
  config.vm.network :public_network, auto_correct: true

  # docker設定をインストール
  config.vm.provision :docker
  config.vm.provision :docker_compose

  # サーバー設定
  config.vm.box_check_update = true
  config.disksize.size = '50GB'
  config.vm.boot_timeout = 600
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'test'
    vb.gui = false
    vb.customize ['modifyvm', :id, '--cpus', '1'] # CPUの数
    vb.customize ['modifyvm', :id, '--memory', '2000'] # メモリ
    vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['modifyvm', :id, '--cpuexecutioncap', '50']
  end

  # shell
  config.vm.provision 'shell', inline: <<-SETTING_CHECK
  clear
  echo 'IPは以下となります'
  ip a
  echo ''
  SETTING_CHECK
end
